### ISSUE TITLE
CA user deletion

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#194]
Hi Lijun,
We have a use case to delete the CA user. We are achieving it by executing the following commands
1. Get all the Certs for this User. Delete each certificate one after other using the command
  ca:rm-cert --ca <caname> -s <serial num>
2. Remove the user from CA
  ca:causer-rm --user <username> --ca <caname>
3. Remove the user
  ca:user-rm --name <username>
The whole operation takes some time to complete. Is there any CLI commands which
1. automatically remove all the dependencies that is remove user removes all the certificates automatically
2. Remove multiple certificates in a single command

**Comment by xipki** [comment]
Removing certificates should only be executed in urgent case. It is a very dangerous operation. Since after that, you cannot manage the status. That means, you cannot revoke a certificate. So the command rm-cert is not intended to remove batch certificates.

If you decide to delete user, with consideration of the security risk, you can modify the database directly via SQL queries.

BTW, why do you need to remove the user? You can just deactivate it use the command ca:user-up.

**Comment by xipki** [comment]
won't implement.
