### ISSUE TITLE
Standalone OCSP responder

### ISSUE THREAD

**Issue by plpzg** [xipki/xipki#198]
Hi,
I have a question - can the OCSP responder be run autonomously, without CA?

How can I import my own certificates to the xipki database? I have a database of certificates in the XCA tool, and I wonder how can I import them into XIPKA?

Thank you.

**Comment by xipki** [comment]
First yes, OCSP responder can be operated without the CA. Currently CRL, EJBCA database, and XiPKI database are supported. To use OCSP responder for other store types, e.g. XCA store, one needs to add a new class which implements the Interface org.xipki.ocsp.api.OcspStore. An example can be found in https://github.com/xipki/xipki/tree/master/examples/ocsp-store-example.

**Comment by plpzg** [comment]
CRL - Can you tell me more details about this solution  ?
How to import  non-revoked certifacates to XIPKI Database based on CRL ?

Thank you.

**Comment by xipki** [comment]
To use CRL in the OCSP responder, please download the https://github.com/xipki/xipki/releases/download/v5.3.11/ocsp-war-5.3.11.zip, you will find the instruction in the unpacked xipki/crls/template/README.

Importing certificates to XiPKI database is for your case not the best solution. Since you need to reimport them once there are chagnes, e.g. new certificates, revocation, etc. Which XCA version do you use?

**Comment by plpzg** [comment]
OK, thank you for your response.

XCA v. 2.1.2
