### ISSUE TITLE
XIPKI in docker container 

### ISSUE THREAD

**Issue by plech-sec** [xipki/xipki#205]
Hi, I would like to ask, what are the possible problems with XIPKI containerization? Is it possible at all with such a complex architecture? Have you tested such a case?

Thank you very much for your answer.

**Comment by xipki** [comment]
I am not familiar with container technologies. If you can have a container with tomcat, you should be able to run xipki software.

**Comment by fuchsia74** [comment]
Yes, deploy XIPKI is a complex work, I have put XIPKI into docker, just use offical tomcat and mariadb docker images. I am still studying xipki, everything looks normal so far.

**Comment by xipki** [comment]
@fuchsia74 Thank you! Could you please share your result?

**Comment by fuchsia74** [comment]
@xipki 
I created a git, ca is running normally, but ocsp is not running normally. These dockerfiles are for reference.

**Comment by plpzg** [comment]
Hi Lijun, fuchsia74.
I have containerized an OCSP responder with a CRL as the data source. ( I used alpine instead of a tomcat docker image) 

A few important passages below 

`FROM alpine:latest

# set env
ENV JAVA_HOME="/usr/lib/jvm/default-jvm"
ENV PATH="$JAVA_HOME/bin:$PATH"
ENV CATALINA_HOME="/opt/apache-tomcat-9.0.44"

RUN apk --no-cache add openjdk11 --repository=https://dl-cdn.alpinelinux.org/alpine/edge/community \
&& apk --no-cache add wget \
&& apk --no-cache add p7zip \
&& apk --no-cache add ca-certificates \
&& rm -rf /var/cache/apk/*
`
```
# create non-root user
RUN addgroup -S -g 10000 xipki \
&& adduser -S -u 10000 xipki -G xipki 
```
``
# fix permissions (especially for running as non-root)
# https://github.com/docker-library/tomcat/issues/35

RUN chmod -R 777 ${CATALINA_HOME}/logs \
&& chmod -R 777 ${CATALINA_HOME}/work \
&& chmod -R 777 ${CATALINA_HOME}/temp

```
WORKDIR ${CATALINA_HOME}
EXPOSE 8080
USER xipki
CMD ["/opt/apache-tomcat-9.0.44/bin/catalina.sh","run"]
```

**Comment by xipki** [comment]
Linked in the project's README.

**Comment by xipki** [comment]
I start a discussion https://github.com/xipki/xipki/discussions/249 for docker container. Please discuss there.
