### ISSUE TITLE
Extending/Reducing the validity of certificates

### ISSUE THREAD

**Issue by subyphilip** [xipki/xipki#229]
By default, CA certificate has validity of 10 years and certificate issued has validity of 5 years. Could you please confirm how
1. the validity of CA can be extended or reduced?
2. the validity of certificate issued by CA can be extended or reduced?

**Comment by xipki** [comment]
The validity of a certificate to be issued in specified by the corresponding cerptofile configuration. E.g. for the certificate profile certprofile-tls.json, the following line says that the certificate will have the validity of 5 year. 
```
"validity":"5y",
```

There is another location specify the maximal validity of the certificates issued by the given CA. This is specified in the file `template.ca-conf.json`:
```
"maxValidity":"10y",
```

You can use the unit `y` for year, `w` for week, `d` for day, `h` for hour, and `m` for minute.

If you have not configure the CA system, you can configure the CA as usual. 

Otherwise, after the change of the certprofile file, you need to load it to the existing CA database.

- To change the maximal validity of CA, use command
  ```
  ca:ca-up
  ```

- To change the existing certprofile, use command
  ```
  ca:profile-up
  ```

- To add new certprofile, use command 
  ```
  ca:profile-add
  ```
