### ISSUE TITLE
HSM Vendor configurations

### ISSUE THREAD

**Issue by vitorcabral94** [xipki/xipki#275]
Hi there,

I'm using the jpkcs11wrapper dependency and I noticed that you have some vendor configuration that changes mechanisms values for different HSM's, but this config is hardcoded to search for your specific file that contains support for TASS and SANSEC HSM, so I can't add new configs for others HSM's.

This is something you intent to add in the future? By this I mean insert the possibility of adding my own vendor.conf file or just add new HSM configurations. If not, how can I contribute for this? Because adding to vendor.conf at this moment won't work because the initVector method of class PKCS11Module is very static for the configs you have.

Thank you, appreciate your work here, the library is getting more awesome to use after each version :)

**Comment by vitorcabral94** [comment]
Hi,

Yes, I'm currently upgrading the jpkcs11wrapper version from 1.0.1 that I was using, to 1.0.4 which is very helpful on managing sessions on it's own .

Can you give me an brief explanation about VENDOR_BEHAVIORS? I can't really understand how it works! And I can't customize the name for example from CKK_VENDOR_SM2 to CKK_SOMETHING_SM2?

Really appreciate the help!

**Comment by xipki** [comment]
Taking CKK_VENDOR_SM2 as example, it specifies the constant value to the SM2 key type. Since SM2 key type is not specified in the PKCS#11 standard, each HSM vendor may use different constant value. In the java code, I assign CKM_VENDOR_SM2 = 0xFFFFF001L (see https://github.com/xipki/jpkcs11wrapper/blob/main/src/main/java/org/xipki/pkcs11/wrapper/PKCS11Constants.java#L1240). In the vendor.conf you may override this with the value defined by the HSM vendor.

**Comment by vitorcabral94** [comment]
Hi,

Sorry, didn't notice that I created the issue in the root of the repositories, my bad!

Thank you for all the information, now I know how to configure those mechanisms.

**Comment by xipki** [comment]
Please also take a look at xipki/ipkcs11wrapper. It supports more algorithms.
